# fly.toml app configuration file generated for soudane-bot on 2023-06-26T23:18:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "soudane-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]